// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trpo_task_25_11;

#nullable disable

namespace trpo_task_25_11.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221205205910_createTableEntr")]
    partial class createTableEntr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("trpo_task_25_11.Entrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Biology")
                        .HasColumnType("int");

                    b.Property<int>("Chemistry")
                        .HasColumnType("int");

                    b.Property<int>("ForeignLang")
                        .HasColumnType("int");

                    b.Property<int>("Informatics")
                        .HasColumnType("int");

                    b.Property<int>("Math")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PE")
                        .HasColumnType("int");

                    b.Property<int>("Physics")
                        .HasColumnType("int");

                    b.Property<int>("RusLang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Entrants");
                });

            modelBuilder.Entity("trpo_task_25_11.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("AvgNote")
                        .HasColumnType("float");

                    b.Property<int>("EntrantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrantId")
                        .IsUnique();

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("trpo_task_25_11.History", b =>
                {
                    b.HasOne("trpo_task_25_11.Entrant", "Entrant")
                        .WithOne("History")
                        .HasForeignKey("trpo_task_25_11.History", "EntrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrant");
                });

            modelBuilder.Entity("trpo_task_25_11.Entrant", b =>
                {
                    b.Navigation("History")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
